### ISSUE TITLE
[BUG] Debian family python package

### ISSUE THREAD

**Issue by OrangeDog** [saltstack-formulas/ufw-formula#19]
On debian, this formula always tries to install `python-ufw`.

- If running salt on python3, this package does nothing.
- Latest releases (e.g. Ubuntu 20.04) don't have this package.

**Comment by OrangeDog** [comment]
A workaround
```yaml
extend:
  ufw-package-python-ufw-install-pkg-installed:
    pkg:
      - onlyif:
        - fun: test.false
```
