### ISSUE TITLE
State 'ufw.enabled' was not found in SLS 'ufw'

### ISSUE THREAD

**Issue by remichristiaan** [saltstack-formulas/ufw-formula#4]
Hi,

I ran into a problem getting ufw-formula to work on my configuration. Hope someone can shed light on this matter. 

When I run: salt-call state.apply common.ufw  test=True (on the minion)

I get the following result:
```
----------
          ID: ufw-app-limit-Saltmaster
    Function: ufw.limit
      Result: False
     Comment: State 'ufw.limit' was not found in SLS 'ufw'
              Reason: 'ufw.limit' is not available.
     Changes:
----------
          ID: ufw-app-allow-OpenSSH
    Function: ufw.allow
      Result: False
     Comment: State 'ufw.allow' was not found in SLS 'ufw'
              Reason: 'ufw.allow' is not available.
     Changes:
----------
          ID: enable-ufw
    Function: ufw.enabled
      Result: False
     Comment: State 'ufw.enabled' was not found in SLS 'ufw'
              Reason: 'ufw.enabled' is not available.
     Changes:

Summary for local
------------
Succeeded: 7 (unchanged=1, changed=1)
Failed:    3
------------
```
_Left out the succeeded ones_

I've configured ufw-formula the same way as I did with e.g. users-formula and openssh-formula:

/srv/salt/common/init.sls
```
include:
  - common.ufw
  - common.openssh
  - common.packages
  - common.users
```
/srv/salt/common/ufw.sls
```
include:
  - ufw
```
/srv/pillar/common/init.sls
```
include:
  - common.ufw
  - common.openssh
  - common.users

```
/srv/pillar/common/ufw.sls
```
ufw:

  enabled: True

  settings:

    loglevel: low
    ipv6: False

  # Allow applications defined at /etc/ufw/applications.d/
  applications:

    OpenSSH:
      enabled: True
      comment: Allow access to the SSH server

    Saltmaster:
      limit: True
      comment: Limit access to the salt master
```
The ufw-formula was git cloned to my formula directory, registered with the master (which was restarted several times). 

Your assistance in this matter is greatly appreciated.
